### PR TITLE
Add example supporting zikin

### PR DESCRIPTION
**Pull request by cmoulliard**
- Instead of a test case, a real example has been created to cover #91 
- Project has been tested using minishift or minikube

### CODE REVIEW

**Comment by iocanel** [comment]
I am not so sure about the example.

- It doesn't feel concise. (lot of different methods that are not obvious how they fit together: start, call, hi etc). 
- It does a lot of things manually, that are not needed (no need to create spans, by hand, not sure about tags).

**Comment by cmoulliard** [comment]
Code is coming from Spring Cloud Sleuth example. I will improve it

**Comment by iocanel** [comment]
@cmoulliard: Then I may miss something obvious here. 
@spencergibb: Your thoughts?

**Comment by cmoulliard** [comment]
@iocanel I think that the idea of Spencer was to demonstrate the Spring Sleuth possibilities as presented within this [publication](http://www.baeldung.com/spring-cloud-sleuth-single-application). This is the reason why different endpoints have been created ....

**Comment by spencergibb** [comment]
Using the sleuth api's shouldn't be the focus, just a sample running in kubernetes is the value I see.

**Comment by cmoulliard** [comment]
> focus

I will revamp the code to just expose 2 endpoints to show a trace and trace + span when a service call another one in order to simplify the lines of code

**Comment by cmoulliard** [comment]
@spencergibb @iocanel Can you review my modifications please ?

**Comment by iocanel** [comment]
This looks ok to me!

I am not crazy about mixing the explicit (using the Tracer) and aop style together (cause its not obvious which is the minimum required configuration to make it work.
 
Maybe in the future they could be two distinct examples.

**Pull request merged**
