### PR TITLE
Add tests case covering Spring Profile

### PR DESCRIPTION
**Pull request by cmoulliard**
- Add tests case covering Spring Profile (kubernetes vs dev)  to better document Issue #88

### CODE REVIEW

**Comment by cmoulliard** [comment]
Do we have to relaunch the job as it returned ?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (javadoc) on project spring-cloud-kubernetes: Execution javadoc of goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar failed: Plugin org.apache.maven.plugins:maven-javadoc-plugin:2.10.4 or one of its dependencies could not be resolved: Failed to collect dependencies at 
org.apache.maven.plugins:maven-javadoc-plugin:jar:2.10.4 -> org.apache.maven.shared:maven-invoker:jar:2.2: Failed to read artifact descriptor for org.apache.maven.shared:maven-invoker:jar:2.2: Could not transfer artifact org.apache.maven.shared:maven-shared-components:pom:21 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local):
Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/apache/maven/shared/maven-shared-components/21/maven-shared-components-21.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
```

**Comment by cmoulliard** [comment]
Do we have to relaunch the job as it returned ? @iocanel @spencergibb

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (javadoc) on project spring-cloud-kubernetes: Execution javadoc of goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar failed: Plugin org.apache.maven.plugins:maven-javadoc-plugin:2.10.4 or one of its dependencies could not be resolved: Failed to collect dependencies at 
org.apache.maven.plugins:maven-javadoc-plugin:jar:2.10.4 -> org.apache.maven.shared:maven-invoker:jar:2.2: Failed to read artifact descriptor for org.apache.maven.shared:maven-invoker:jar:2.2: Could not transfer artifact org.apache.maven.shared:maven-shared-components:pom:21 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local):
Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/apache/maven/shared/maven-shared-components/21/maven-shared-components-21.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
```

**Comment by iocanel** [comment]
What exactly are we trying to test here? 
This look like it tests spring itself, rather than spring cloud kubernetes.
Do I miss something?

**Comment by cmoulliard** [comment]
> Do I miss something?

No. The idea of the test case is to demonstrate what will happen if the Kubernetes profile is used or not. Ideally it should run in a Kubernetes Mocked Server to verify that the profile is [active or not](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileApplicationListener.java#L57)

**Comment by iocanel** [comment]
If I remember correctly the `kubernetes` detection happen by checking the existence of files and environment variables, so we can't mock it.

Since, this test is not actually testing s.p.k I would prefer we keep it out.

**Pull request closed without merging**
