### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by FedericoPonzi**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@FedericoPonzi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=186)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=186) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@FedericoPonzi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=186)!

**Comment by Salaboy** [comment]
This is just a typo, so it should be merged

**Comment by iocanel** [comment]
Thanks @FedericoPonzi

**Pull request merged**
