### PR TITLE
Update spring-cloud-* versions

### LINKED ISSUE #82: Update spring-cloud-netflix & sleuth dependencies
As spring-cloud-netflix & sleuthprojects have been released, we should update these versions 

https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/blob/master/pom.xml#L62-L64

```
<spring-cloud-commons.version>1.1.7.BUILD-SNAPSHOT</spring-cloud-commons.version>
<spring-cloud-netflix.version>1.2.4.BUILD-SNAPSHOT</spring-cloud-netflix.version>
<spring-cloud-sleuth.version>1.1.1.BUILD-SNAPSHOT</spring-cloud-sleuth.version>
```

to use

```
<spring-cloud-commons.version>1.2.0.RELEASE</spring-cloud-commons.version>
<spring-cloud-netflix.version>1.3.0.RELEASE</spring-cloud-netflix.version>
<spring-cloud-sleuth.version>1.2.0.RELEASE</spring-cloud-sleuth.version>
```

### PR DESCRIPTION
**Pull request by cmoulliard**
Update spring-cloud-netflix, spring-cloud-sleuth & commons to use RELEASE versions instead of SNAPSHOT. Fix #82

### CODE REVIEW

**Comment by cmoulliard** [comment]
@iocanel Can you review/approve please ?

**Comment by iocanel** [comment]
@cmoulliard: There are compile failures in circleci. These need to be addressed.

**Comment by cmoulliard** [comment]
Here is the error reported

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5:compile (default-compile) on project spring-cloud-kubernetes-zipkin: Compilation failure
[ERROR] /home/ubuntu/spring-cloud-kubernetes/spring-cloud-kubernetes-zipkin/src/main/java/org/springframework/cloud/kubernetes/zipkin/ZipkinKubernetesAutoConfiguration.java:[62,46] incompatible types: java.lang.String cannot be converted to org.springframework.web.client.RestTemplate
```

**Comment by cmoulliard** [comment]
I think that a test case will be required validate the modifications

**Pull request merged**
