### PR TITLE
Obvious Fix: PostgreSQL secret: typo and copy/paste error

### PR DESCRIPTION
**Pull request by sixtyeight**
Obvious Fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sixtyeight Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=76)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=76) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by sixtyeight** [comment]
Obvious Fix

**Comment by iocanel** [comment]
@sixtyeight: I think that you need to sign the CLA. Once this is done we can merge. Thanks again!

**Comment by iocanel** [comment]
@sixtyeight: Shall we wait for the CLA?

**Comment by spencergibb** [comment]
I think he may need manually syncronize. https://cla.pivotal.io/about Putting Obvious Fix in the description should do it, right @rwinch?

**Comment by rwinch** [comment]
I think we have a case sensitivity issue...let's try....

This is an obvious fix

**Comment by pivotal-issuemaster** [comment]
@sixtyeight This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by rwinch** [comment]
FYI...I fixed the case sensitivity issue and it is now deployed to production.

**Pull request merged**
