### PR TITLE
Add dc.yaml file 

### LINKED ISSUE #55: HelloWorld can't be deployed in minikube - docker image not found
The deployment of the HelloWorld in minikube generates 

```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.17.1/minikube-darwin-
amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
minikube start
mvn clean package fabric8:deploy
```

generates this error

```
Failed to pull image "cloud/kubernetes-hello-world:snapshot-170324-194007-0653": Error: image cloud/kubernetes-hello-world not found
Error syncing pod, skipping: failed to "StartContainer" for "spring-boot" with ErrImagePull: "Error: image cloud/kubernetes-hello-world not found"
```

screenshot 2017-03-24 19 40 42

Kubernetes yaml file generated by f-m-p

```
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 16b4eaf0016aedfb255cce4c5ea4bc4a4a14a7f3
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      provider: fabric8
      project: kubernetes-hello-world
      version: 0.2.0.BUILD-SNAPSHOT
      group: org.springframework.cloud
    name: kubernetes-hello-world
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: kubernetes-hello-world
      provider: fabric8
      group: org.springframework.cloud
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 16b4eaf0016aedfb255cce4c5ea4bc4a4a14a7f3
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kubernetes-hello-world&var-version=0.2.0.BUILD-SNAPSHOT
      fabric8.io/docs-url: scp://static.springframework.org/var/www/domains/springframework.org/static/htdocs/spring-cloud/docs/kubernetes-hello-world/0.2.0.BUILD-SNAPSHOT/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
    labels:
      provider: fabric8
      project: kubernetes-hello-world
      version: 0.2.0.BUILD-SNAPSHOT
      group: org.springframework.cloud
    name: kubernetes-hello-world
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: kubernetes-hello-world
        provider: fabric8
        group: org.springframework.cloud
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 16b4eaf0016aedfb255cce4c5ea4bc4a4a14a7f3
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kubernetes-hello-world&var-version=0.2.0.BUILD-SNAPSHOT
          fabric8.io/docs-url: scp://static.springframework.org/var/www/domains/springframework.org/static/htdocs/spring-cloud/docs/kubernetes-hello-world/0.2.0.BUILD-SNAPSHOT/spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world
        labels:
          provider: fabric8
          project: kubernetes-hello-world
          version: 0.2.0.BUILD-SNAPSHOT
          group: org.springframework.cloud
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: cloud/kubernetes-hello-world:snapshot-170324-203655-0857
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          securityContext:
            privileged: false
```

### PR DESCRIPTION
**Pull request by cmoulliard**
- Add dc.yaml file under src/main/fabric8 to fix the docker image to use as version latest. In this case, the docker image will be found.
- Fix #55

### CODE REVIEW

**Comment by iocanel** [comment]
@cmoulliard: wouldn't using an `<image>` element in the f-m-p configuration, have the same effect?

**Comment by cmoulliard** [comment]
This is another option that we can adopt to include the `<image>` tag within the configuration section of the f-m-p plugin instead of using a dc.yaml file

```
<configuration>
  <images>  
    <image>
      <name>cloud/kubernetes-hello-world:latest</name>
```

**Comment by cmoulliard** [comment]
Adding the missing goal <goal>build</goal> to f-m-p resolves the issue with the docker image snapshot not found but CI now is failing. Question : Do we have to setup another profile to avoid this problem ?

**Comment by iocanel** [comment]
How about creating an additional profile called `docker` that will also include the **fabric8:build** goal. Pretty much like the `integration` profile but without the integration tests themselves.

**Comment by cmoulliard** [comment]
I will do this modification but will use as profile name -Pkubernetes as f-m-p build the docker image and next deploy the kubernetes resources

**Comment by iocanel** [comment]
@cmoulliard: LGTM

Can you please squash the three commits into one?

**Comment by iocanel** [comment]
@cmoulliard @spencergibb: I'd like to merge this, so that I can merge the rest of the pending pull requests.

For some reason, I can't see why circleci fails? Can any of you see and paste the error?

**Comment by cmoulliard** [comment]
@iocanel The build 60 fails as the pom still includes the goal build

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.28:build (fmp) on project kubernetes-hello-world: Execution fmp of goal io.fabric8:fabric8-maven-plugin:3.2.28:build failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured -> [Help 1]
[ERROR] 
```

**Comment by iocanel** [comment]
@cmoulliard: thanks! I must have broken that when I rebased your commits into one. Added an additional commit to fix that.

**Pull request merged**
