### PR TITLE
Add important documentation.

### PR DESCRIPTION
**Pull request by computerlyrik**
It took me a while to find out why the discoveryClient did only return empty attributes (e.g. serviceList) .

Adding `@EnableDiscoveryClient` fixed this for me.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@computerlyrik Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=144)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=144) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by iocanel** [comment]
@computerlyrik: This can't be merged unless the CLA  is signed.

**Comment by pivotal-issuemaster** [comment]
@computerlyrik Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=144)!

**Comment by computerlyrik** [comment]
@iocanel  Signed and manually synced status.

**Pull request merged**
