### PR TITLE
Add logback-test.xml file to change the logging level of hibernate validator

### LINKED ISSUE #53: Too many hibernate debug messages are logged
When the Arquillian Integration Test is executed, hundred of lines are reported with DEBUG level about Hibernate Validator

```
cd spring-cloud-kubernetes/spring-cloud-kubernetes-examples/kubernetes-hello-world-example
mvn clean install -Pintegration

17:57:32.192 [main] DEBUG org.hibernate.validator.internal.engine.resolver.DefaultTraversableResolver - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
17:57:32.192 [main] DEBUG org.hibernate.validator.internal.xml.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
17:57:32.192 [main] DEBUG org.hibernate.validator.internal.xml.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
17:57:32.192 [main] DEBUG org.hibernate.validator.internal.xml.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
...
```

This problem can be solved by adding within the logback.xml file the info level for hibernate validator

### PR DESCRIPTION
**Pull request by cmoulliard**
Add logback-test.xml file to change the logging level of hibernate validator to info. Fix #53

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cmoulliard Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=54)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=54) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by cmoulliard** [comment]
@pivotal-issuemaster I'm working like Ioannis Cannellos for Red Hat which has already signed such CLA doc.

**Comment by spencergibb** [comment]
@cmoulliard according to the cla app

> I should be covered under a Corporate Signature. Do I Need to Sign Again?
> No. A corporate signature is either associated to the domain of a verified email address or a GitHub organization.

See https://cla.pivotal.io/about

**Comment by pivotal-issuemaster** [comment]
@cmoulliard Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-kubernetes&pullRequestId=54)!

**Pull request merged**
